#!/bin/bash

cd ../mdb

ls -1 |grep .mdb | while read f 

do

	echo "------------------File: $f"

	mdb-tables $f -1 | while read line

	do
		
		jsonfile=../json/${f/mdb}$line.json

		echo "----------Reading from $f table $line and writing $jsonfile"

		mdb-json $f $line > $jsonfile

	done

done
